apiVersion: v2
name: user-service
description: user-service for e-commerce platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ecommerce
  - microservice
dependencies:
  - name: microservices-base-chart
    version: "1.0.0"
    repository: "file://../../../microservices-base-chart"

